### ISSUE TITLE
Would be great to have capability to group different callables with their execution frequency in a single tagged service?

### ISSUE THREAD

**Issue by vishalmelmatti** [TDMobility/Symfony2TaskScheduler#1]
Hi,

Great work ! This is what I was exactly looking for. Do I need to create separate service for each task (in my case these are just some monitoring checks which I want to run at different frequency)  ? 

It would be great to if we could group different related callable in single service instead of creating and configuring service for each task.

Thanks

**Comment by westinpigott** [comment]
yes, they way it is currently written, you need to have a separate class/service for each task.  In order to achieve what you are asking, you could inject the various services in the "group" into the task service.  Then call each of them from within the "execute" method.
